# This workflow is used to create a PR with the existing agent version from the test branch to main

name: Sync Agent Version to main

# Controls when the workflow will run
on:
  push:
    branches: [ "test" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  open-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          env
          ls
          cat instana/com.instana.agent.bootstrap.AgentBootstrap.cfg
          TMP_BOOTSTRAP_DIR=$(mktemp)
          cp instana/com.instana.agent.bootstrap.AgentBootstrap.cfg ${TMP_BOOTSTRAP_DIR}/
          git checkout main
          git checkout -b promote-test-to-main
          cp -f ${TMP_BOOTSTRAP_DIR}/com.instana.agent.bootstrap.AgentBootstrap.cfg instana/com.instana.agent.bootstrap.AgentBootstrap.cfg
          git add instana/com.instana.agent.bootstrap.AgentBootstrap.cfg
          git commit -m "chore: Sync AgentBootstrap from current test branch"
          git push origin -f promote-test-to-main
          
          
